### ISSUE TITLE
Use relative module resolver for react

### ISSUE THREAD

**Issue by michalkowol** [codeloopeu/thehub#17]
Depends on: #10

Library: [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver)

**Comment by kotoko** [comment]
Added in 0157c827d0e8af66769a6257cd20fadd1ea26487 .

**Comment by kotoko** [comment]
I used [rescripts](https://github.com/harrysolovay/rescripts). 

Generally react-scripts does not allow configuring babel without ejecting. There are packages that change something in how react-scripts works but it can break things someday. I used one of those packages.
