### ISSUE TITLE
Change package and all occurence of `com.softwareberg` to `eu.codeloop`

### ISSUE THREAD

**Issue by michalkowol** [codeloopeu/thehub#8]
Change:
* `com.softwareberg` -> `eu.codeloop`
* `softwareberg` -> `codeloop`

**Comment by kotoko** [comment]
I changed every code occurrence. Almost works - can't connect to database after that. For some reason postgres still has old username and password configured. Maybe my docker trolls me...

**Comment by michalkowol** [comment]
`docker-compose up -d --force-recreate --build`

**Comment by kotoko** [comment]
Merged.
